version: '3'
services:
  # Goアプリケーションのサービス
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    # volumes:
    #   - ./:/go/src/app
    environment:
      - MYSQL_HOST=MySQL
    # environment:
    #   DB_HOST: db
    #   DB_PORT: "3306"
    #   DB_USER: root
    #   DB_PASSWORD: password
    #   DB_NAME: app
    networks:
      - app-network

  # MySQLデータベースのサービス
  db:
    image: mysql:latest
    container_name: MySQL
    tty: true
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    external: true
